### ISSUE TITLE
XSAMPA

### ISSUE THREAD

**Issue by xrotwang** [cldf/orthograpy#2]
https://en.wikipedia.org/wiki/X-SAMPA

**Comment by LinguList** [comment]
Problem with x-sampa is, that it in part needs secondary segmentation, and all pitfalls of IPA. So the question is: would it make sense to really treat this as an orthography, given that the segmentation rules themselves are application-specific? 

As an example, consider [cddb/Liu2007](https://github.com/digling/cddb/blob/master/datasets/Liu2007/profile.tsv), where I made a profile based on X-Sampa I wrote myself in order to digitize a dataset by Liu et al. (2007). This is an orthography profile for a given dataset, but probably not the "normal" x-sampa profile one would expect, although x-sampa doesn't answer questions such as if "ts" is one or two sounds, etc.

**Comment by xrotwang** [comment]
Agree. As with the input alphabet for ELAN, I think, we should first determine whether such a profile would have useful applications. Your example seems to suggest "no, not in general".

**Comment by LinguList** [comment]
Yes, unfortunately. We could, however, try to produce an automated version of x-sampa from clts.bipa, but here again, users would probably use a converter with regexes from sampa to ipa, and that'd be it. For the system by @Anaphory, however, it might be interesting, to have a rough ipa-thingy, as he'd be able to merge different profiles into one new profile. But this would go beyond our interest in orthograpy. 

If we find a "proto-typical" sampa dataset, however, we could get back to this. Maybe one of Nerbonne's group, as they used sampa in many applications.

**Comment by LinguList** [comment]
@xrotwang, I now addex an ex-sampa profile. As you can see from the app at [calc/profile](http://calc.digling.org/profile), it works rather well! What I did was using my own private version of key-maps which I use to type sampa and converting those in reverse from our clts masterlist. Result is a rather convincing sampa-converter that also segments at the same time.  In some sense a nice proof of concept for the usefulness of orthoprofiles.
